### ISSUE TITLE
Something wrong with xmpp 

### ISSUE THREAD

**Issue by atyenoria** [robertoandrade/docker-jitsi-meet#7]
This docker image can't work well in my env(local mac).
Peer to peer connection failed.

Browser error is like this 

```
[/modules/xmpp/JingleSessionPC.js] <JingleSessionPC.addSource>:  ice checking
Logger.js:89 [/modules/xmpp/JingleSessionPC.js] <TraceablePeerConnection.peerconnection.oniceconnectionstatechange>:  (TIME) ICE failed:     83712.73500000002
conference.js:229 CONFERENCE FAILED: conference.setup_failed
```

Can anyone help me??

**Comment by atyenoria** [comment]
solved by --net=host option

**Comment by datnguyenthang** [comment]
solved by --net=host option
Where have you fixed?

**Comment by atyenoria** [comment]
What do you mean by Where? 
I added this option with docker run

**Comment by datnguyenthang** [comment]
i tried like that:
docker run --net=host -it --name jitsi-meet -p 443:443 robertoandrade/jitsi-meet
but it still run incorrect with error "CONFERENCE FAILED: conference.setup_failed"

**Comment by atyenoria** [comment]
What kinds of server are you using? aws?
I can't help with this.

**Comment by datnguyenthang** [comment]
I using RHEL santiago 6.6

**Comment by atyenoria** [comment]
Are you sure to check the network config without docker?

**Comment by datnguyenthang** [comment]
I have installed Openmeetings, its worked correctly.

**Comment by atyenoria** [comment]
Do you try to open all of the port when docker run?
```
https://hub.docker.com/r/robertoandrade/jitsi-meet/~/dockerfile/
EXPOSE 80 443 5347
EXPOSE 10000/udp 10001/udp 10002/udp 10003/udp 10004/udp 10005/udp 10006/udp 10007/udp 10008/udp 10009/udp 10010/udp
```

**Comment by datnguyenthang** [comment]
```
CONTAINER ID        IMAGE                       COMMAND                CREATED             STATUS              PORTS                                                     NAMES
c12398567404        robertoandrade/jitsi-meet   "/bin/sh -c /run.sh"   23 minutes ago      Up 23 minutes       80/tcp, 10000-10010/udp, 5347/tcp, 0.0.0.0:443->443/tcp   jitsi-meet 
```


i reconfigured, its still running incorrect

**Comment by atyenoria** [comment]
Unfortunately, beyond my experience...
